- include_vars: vault/main.yaml
- name: Install xinetd
  yum: name=xinetd update_cache=yes

- name: Create the checker users
  mysql_user:
    login_user: "{{ mariadb_root_name }}"
    login_port: "{{ mariadb_port }}"
    login_password: "{{ mariadb_root_passwd }}"
    name: haproxyUser
    host: localhost
    password: "{{ checker_passwd }}"
    state: present
  when: mysql_repl_role == 'master'

- name: Install script
  template:
    src: galeracheck.sh.j2
    dest: /usr/local/bin/galeracheck.sh
    owner: nobody
    group: nobody
    mode: 0744
  when: monitor_what == "galera"

- name: Install script
  template:
    src: replicationcheck.sh.j2
    dest: /usr/local/bin/replicationcheck.sh
    owner: nobody
    group: nobody
    mode: 0744
  when:
  - monitor_what == "replication"

- name: Install mysqlchk in xinetd.d
  template: src=mysqlchk.j2 dest=/etc/xinetd.d/mysqlchk owner=root group=root mode=0644

- name: Add service into /etc/services
  lineinfile:
    dest: /etc/services
    line: 'mysqlchk 9302/tcp'
    state: present

- name: enable and restart xinetd
  service: name=xinetd enabled=yes state=restarted
