- include_vars: vault/main.yaml
- name: Test get msg
  debug: msg="read {{ os.distribution_centos.name }} install version {{ version }}"

- name: Install MongoDB 2x repo
  copy: src=MongoDB2.repo.j2 dest=/etc/yum.repos.d/MongoDB.repo
  when: version == 2

- name: Install MongoDB 3x repo
  copy: src=MongoDB3.repo.j2 dest=/etc/yum.repos.d/MongoDB.repo
  when: version == 3

- name: Install MongoDB
  yum: name=mongodb-org update_cache=yes 

- name: Get pip
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp/get-pip.py mode=0644
 
- name: Install pip
  command: /usr/bin/python get-pip.py
  args:
    chdir: /tmp

- name: Install pymongo
  pip: name=pymongo 

- name: Config MongoDB
  template: src=mongod.conf.j2 dest=/etc/mongod.conf backup=yes
  tags: reconfig

- name: Change ulimit
  copy: src=mongod_ulimit.j2 dest=/etc/security/limits.d/90-mongodb.conf  

- name: Create transparent huge page script
  copy: src=disable_transparent_hugepages.j2 dest=/etc/init.d/disable-transparent-hugepages
  
- name: Change mode transparent huge page script
  file: path=/etc/init.d/disable-transparent-hugepages mode=755

- name: Create new profile
  file: path=/etc/tuned/no-thp state=directory mode=0755
  when:
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version7 }}"

- name: Create tuned.conf
  copy: src=tuned.conf.j2 dest=/etc/tuned/no-thp/tuned.conf
  when: 
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version7 }}"

- name: Enable new profile
  command: tuned-adm profile no-thp
  when:
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version7 }}"

- name: Create /etc/systemd/system/mongod.service.d
  file: path=/etc/systemd/system/mongod.service.d state=directory mode=0755  
  when:
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version7 }}"

- name: Customize mongod service script
  copy: src=mongod_service_limits.conf.j2 dest=/etc/systemd/system/mongod.service.d/10_limits.conf 
  when:
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version7 }}"

- name: Enable and start transparent huge page script
  service: name=disable-transparent-hugepages enabled=yes state=restarted

- name: Enable and start mongod on centos 6
  service: name=mongod enabled=yes state=restarted
  when:
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version6 }}"
  tags: restart_mongod

- name: Enable and start mongod on centos 7
  systemd: name=mongod daemon_reload=yes state=restarted enabled=yes
  when:
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version7 }}"
  tags: restart_mongod

- name: Create admin users
  mongodb_user:
    database: "{{ item.db }}"
    name: "{{ item.name }}"
    password: "{{ item.passwd }}"
    roles: "{{ item.roles }}"
    login_host: localhost
    login_port: "{{ config.net.port }}"
  with_items: "{{ admin_users }}"
  ignore_errors: yes
