- name: Setup deployer user
  hosts: all

  vars:
    ansible_deployers:
      file: /etc/sudoers.d/ansible
      group: "{{ vault_deployer_group }}"
      users:
        - name: "{{ vault_deployer_name }}"
          passwd: "{{ vault_deployer_passwd }}"
          full_name: "{{ vault_deployer_full_name }}"
  tasks:
    - name: Make sure we have deployer group
      group:
        name: "{{ ansible_deployers.group }}"
        state: present

    - name: Create sudoers for deployer group
      template:
        src: ansible.conf.j2
        dest: "{{ ansible_deployers.file }}"
        owner: root
        group: root
        mode: 0440
        validate: 'visudo -cf %s'

    - name: Add deployer user to deployer group
      user:
        name: "{{ item.name }}"
        password: "{{ item.passwd }}"
        comment: "{{ item.full_name }}"
        groups: "{{ ansible_deployers.group }}"
        append: yes
      with_items: "{{ ansible_deployers.users }}"

    - name: Check if filter user in sshd
      command: grep -Fq "AllowUsers" /etc/ssh/sshd_config
      register: check_sshd
      ignore_errors: yes
      changed_when: False
      check_mode: no

    - name: Allow user deployer in sshd
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: 'AllowUsers {{ item.name }}'
        state: present
        validate: '/usr/sbin/sshd -T -t -f %s'
      with_items: "{{ ansible_deployers.users }}"
      when: check_sshd.rc == 0

    - name: Restart sshd
      service: name="sshd" enabled=yes state=restarted
      when: check_sshd.rc == 0

    - name: Copy ssh key to authorized_keys
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ lookup('file', '/etc/.ssh/ansible_id_rsa.pub') }}"
      with_items: "{{ ansible_deployers.users }}"

