- name: Create the lastest MariaDB repo
  copy: src=MariaDB-lastest.repo.j2 dest=/etc/yum.repos.d/MariaDB.repo

- name: Create GPG key for MariaDB repo
  copy: src=RPM-GPG-KEY-MariaDB dest=/etc/pki/rpm-gpg

- name: Add percona repo
  yum: name="{{ percona_url }}" state=present

- name: Clean yum
  command: yum clean all

- name: Install MariaDB lastest package
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
  - MariaDB-client
  - MariaDB-server
  - galera
  - MariaDB-devel
  - python-setuptools
  - percona-xtrabackup
  - percona-toolkit
  - socat

- name: Install MySQL-python lib
  easy_install: name="MySQL-python"
