nginx_version: 1.11.8
nginx_url: "https://nginx.org/download/nginx-{{ nginx_version }}.tar.gz"
nginx_compiling_params: "--prefix={{ nginx_install_dir }} --user={{ nginx_user }} --group={{ nginx_group }} --without-http_autoindex_module --without-http_ssi_module --without-http_map_module --without-http_uwsgi_module --without-http_scgi_module --without-http_empty_gif_module --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_stub_status_module"

nginx_install_dir: /etc/nginx
nginx_vhosts_dir: "{{ nginx_install_dir }}/conf.d"
nginx_conf: "{{ nginx_install_dir }}/conf/nginx.conf"
nginx_log_dir: /var/log/nginx
nginx_base_doc_root: /data
nginx_doc_root: "{{ nginx_base_doc_root }}/www"
nginx_pid: /run/nginx.pid
nginx_error_log: "{{ nginx_log_dir }}/error.log"
nginx_access_log: "{{ nginx_log_dir }}/access.log"

nginx_global_params:
  worker_rlimit_nofile: "4096"
  worker_processes: "1"

nginx_events_params:
  worker_connections: "4096"
  use: "epoll"
  multi_accept: "on"

nginx_http_params:
  client_max_body_size: "8M"
  sendfile: "on"
  tcp_nopush: "on"
  tcp_nodelay: "on"
  keepalive_timeout: "65"

nginx_vhosts_name:
  - hotel.example.com

nginx_vhosts:
  - listen: 80
    name: "{{ nginx_vhosts_name.0 }}"
    server_name: "{{ nginx_vhosts_name.0 }} www.{{ nginx_vhosts_name.0 }}"
    index: "index.php index.html"
    log_dir: "{{ nginx_log_dir }}/{{ nginx_vhosts_name.0 }}"
    access_log: "{{ nginx_log_dir }}/{{ nginx_vhosts_name.0 }}/access.log"
    error_log: "{{ nginx_log_dir }}/{{ nginx_vhosts_name.0 }}/error.log"
    root: "{{ nginx_doc_root }}/{{ nginx_vhosts_name.0 }}"
    client_max_body_size: 20M
    location0: {
        name: /
      }
    location1: {
        name: ~ \.php$,
        fastcgi_pass: "unix:/var/run/php-fpm/php-fpm.sock",
        fastcgi_index: "index.php",
        fastcgi_param: "SCRIPT_FILENAME $document_root$fastcgi_script_name",
        include: "{{ nginx_install_dir }}/conf/fastcgi_params"
      }

### ngx_built: 0|1
ngx_built: 0
