- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yaml"

- include_vars: vault/main.yaml
  tags: include

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ dependent_pkgs }}"
  when: ansible_os_family == 'RedHat'

- name: Create docker-registry directory
  file: path="{{ item }}" state=directory owner=root group=root mode=0755
  with_items:
    - "{{ resgistry_dir }}"
    - "{{ web_dir }}"
    - "{{ data_dir }}"

- name: Copy docker-compose.yaml into docker-registry directory
  copy:
    src: docker-compose.yaml
    dest: "{{ resgistry_dir }}/docker-compose.yaml"
    owner: root
    group: root
    mode: 0644

- name: Copy resgistry.conf into docker-registry directory
  copy:
    src: nginx_registry.conf
    dest: "{{ web_dir }}/registry.conf"
    owner: root
    group: root
    mode: 0644

- name: Create registry password
  file: path="{{ htpasswd_file }}" state=touch owner=root group=root mode=0644

- name: Create admin htpasswd
  command: "htpasswd -b {{ htpasswd_file }} {{ item.name }} {{ item.passwd }}"
  args:
    chdir: "{{ web_dir }}"
  with_items: "{{ auth_users }}"

- name: docker-compose up
  command: "{{ item }} chdir={{ resgistry_dir }}"
  with_items:
    - docker-compose stop
    - docker-compose rm -f
    - docker-compose up -d
