- include_vars: vault/main.yaml
  tags: include

- name: Install Mariadb 10.0.21 on CentOS 6
  copy: src=MariaDB-CentOS6-10.0.21.repo.j2 dest=/etc/yum.repos.d/MariaDB.repo
  when: 
    - version == "10.0.21"
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version6 }}"

- name: Install Mariadb 10.0.21 on CentOS 7
  copy: src=MariaDB-CentOS7-10.0.21.repo.j2 dest=/etc/yum.repos.d/MariaDB.repo
  when:   
    - version == "10.0.21"
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version7 }}"

#- name: Install MariaDB 
#  yum: name="{{ item }}" update_cache=yes 
#  with_items:
#  - MariaDB-client
#  - MariaDB-server
#  - MariaDB-devel

#- name: Add percona repo
#  yum: name="{{ repos.url }}" update_cache=yes
#  when:
#    - ansible_distribution == "{{ repos.distribution_centos }}"

#- name: Install percona-toolkit and percona-xtrabackup
#  yum: name="{{ item }}" update_cache=yes 
#  with_items:
#  - percona-xtrabackup
#  - percona-toolkit

#- name: Get pip
#  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp/get-pip.py mode=0644
 
#- name: Install pip
#  command: /usr/bin/python get-pip.py
#  args:
#    chdir: /tmp

#- name: Install MySQL-python
#  pip: name=MySQL-python

- name: Create dir
  file: path="{{ item }}" state=directory owner=mysql group=mysql
  with_items: 
  - "{{ dir.datadir }}"
  - "{{ dir.logdir }}"
  - "{{ mysqld.tmpdir }}"

- name: Config MariaDB
  template: src=mariadb.conf.j2 dest=/etc/my.cnf.d/server.cnf backup=yes
  tags: reconfig

- name: set vm.swappiness in sysctl.conf
  sysctl: name=vm.swappiness value="{{ sysctl.vm.swappiness }}" state=present sysctl_set=yes reload=yes ignoreerrors=yes

- name: Change ulimit
  copy: src=mysqld_ulimit.j2 dest=/etc/security/limits.d/95-mysqld.conf  

- name: Check if ulimit in service script
  command: grep -Fq "ulimit" /etc/init.d/mysql
  register: check_ulimit_mysql
  ignore_errors: yes
  changed_when: False
  check_mode: no
  tags: change_ulimit

- name: Change limit in service script 
  lineinfile: 
    line: "{{ item }}"
    dest: /etc/init.d/mysql
    insertbefore: '^case \"\$mode\" in'
  with_items:
  - ulimit -u 32000
  - ulimit -n 32000
  when:
  - check_ulimit_mysql.rc != 0
  ignore_errors: yes
  tags: change_ulimit

- name: Create /etc/systemd/system/mariadb.service.d
  file: path=/etc/systemd/system/mariadb.service.d state=directory mode=0755
  when:
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version7 }}"

- name: Customize mariadb service script
  copy: src=mariadb_service_limits.conf.j2 dest=/etc/systemd/system/mariadb.service.d/10_limits.conf 
  when:
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version7 }}"

- name: Enable and start mariadb
  service: name=mysql enabled=yes state=restarted
  tags: restart_mariadb

- name: Update passwd
  mysql_user:
    name: "{{ admin_user.name }}"
    password: "{{ admin_user.passwd }}"
    priv: "{{ admin_user.priv }}"
    state: present
    login_user: "{{ admin_user.name }}"
    login_port: "{{ mysqld.port }}"
    login_host: localhost
    host: "{{ item }}"
  with_items: 
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes

- name: Check mariadb status
  command: service mysql status
  tags: check_service


