- name: install ntpd
  yum: name={{ ntpd_pkg_name }} update_cache=yes
  tags: package

- name: configure ntpd
  template: >
    src=ntpd_config.j2
    dest=/etc/ntp.conf
    backup=yes
  notify: restart ntpd
  tags: configuration

- name: enable ntpd
  service: name={{ ntpd_service_name }} state=started enabled=yes
  tags: service
