- name: Config hostname
  hostname:
    name: "{{ hostname }}"

- name: Config /etc/hosts follow hostname
  lineinfile:
    dest: /etc/hosts
    state: present
    line: '{{ item }}'
  with_items:
    - "127.0.0.1 {{ hostname }}"
#    - "{{ ansible_default_ipv4.address }} {{ hostname }}"
    - "{{ ansible_host }} {{ hostname }}"

- name: Config nameserver
  blockinfile:
    dest: /etc/resolv.conf
    block: |
      {{ nameservers }}
