- name: Create dev group
  group:
    name: "{{ dev_group }}"
    state: present

- name: Create developer accounts
  user:
    name: "{{ item.name }}"
    password: "{{ item.passwd }}"
    comment: "{{ item.full_name }}"
    shell: /bin/bash
    groups: "{{ dev_group }}"
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: item.active == 1
  with_items: "{{ dev_users }}"

- name: Set authorized key took from file
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.public_key }}"
  when: item.active == 1
  with_items: "{{ dev_users }}"

- name: Config basic vim
  copy: src=vimrc.conf.j2 dest="/home/{{ item.name }}/.vimrc"
  when: item.active == 1
  with_items: "{{ dev_users }}"

- name: Config basic tmux
  copy: src=tmux.conf.j2 dest="/home/{{ item.name }}/.tmux.conf"
  when: item.active == 1
  with_items: "{{ dev_users }}"
