- name: Install epel-release
  yum: name="epel-release" update_cache=yes

- name: Install elrepo
  yum:
    name: "{{ elrepo_centos_7_url }}"
    update_cache: yes
  when:
    - ansible_distribution == "{{ distro_centos.name }}"
    - ansible_distribution_major_version == "{{ distro_centos.version7 }}"

- name: Install elrepo
  yum:
    name: "{{ elrepo_centos_6_url }}"
    update_cache: yes
  when:
    - ansible_distribution == "{{ distro_centos.name }}"
    - ansible_distribution_major_version == "{{ distro_centos.version6 }}"

- name: Install elrepo
  yum:
    name: "{{ elrepo_centos_5_url }}"
    update_cache: yes
  when:
    - ansible_distribution == "{{ distro_centos.name }}"
    - ansible_distribution_major_version == "{{ distro_centos.version5 }}"

- name: Install remi repo
  yum:
    name: "{{ remi_centos_7_url }}"
    update_cache: yes
  when:
    - ansible_distribution == "{{ distro_centos.name }}"
    - ansible_distribution_major_version == "{{ distro_centos.version7 }}"

- name: Install remi repo
  yum:
    name: "{{ remi_centos_6_url }}"
    update_cache: yes
  when:
    - ansible_distribution == "{{ distro_centos.name }}"
    - ansible_distribution_major_version == "{{ distro_centos.version6 }}"

- name: Install remi repo
  yum:
    name: "{{ remi_centos_5_url }}"
    update_cache: yes
  when:
    - ansible_distribution == "{{ distro_centos.name }}"
    - ansible_distribution_major_version == "{{ distro_centos.version5 }}"

- name: Get pip
  get_url: url="{{ pip_url }}" dest=/tmp/get-pip.py mode=0644

- name: Install pip
  command: /usr/bin/python get-pip.py
  args:
    chdir: /tmp

- name: Install libselinux-python
  yum: name=libselinux-python update_cache=yes

- name: Install monitoring and debuging package
  yum: name="{{ item }}" update_cache=yes
  with_items: "{{ packages }}"
