- include_vars: vault.yaml
- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Config /etc/hosts follow hostname
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 {{ hostname }}'
    
- name: Config temporary gateway
  command: route add default gw "{{ gateway.ip }}"
  ignore_errors: yes

- name: Config persistent gateway
  lineinfile:
    dest: /etc/sysconfig/network
    state: present
    regexp: '^GATEWAY='
    line: 'GATEWAY={{ gateway.ip }}'
  when: gateway.keep

- name: Config nameserver
  blockinfile:
    dest: /etc/resolv.conf
    block: |
      {{ nameservers }}

#- name: Install epel-release
#  yum: name="epel-release" update_cache=yes

#- name: Debug
#  debug: msg="URL= {{ item.url }}"
#  with_items: "{{ repos }}"

#- name: Install elrepo
#  yum:
#    name: "{{ item.url.0 }}"
#    update_cache: yes
#  when:
#    - ansible_distribution == "{{ item.distribution }}"
#    - ansible_distribution_major_version == "{{ item.distribution_major_version }}"
#  with_items: "{{ repos }}"

#- name: Install remi repo
#  yum:
#    name: "{{ item.url.1 }}"
#    update_cache: yes
#  when:
#    - ansible_distribution == "{{ item.distribution }}"
#    - ansible_distribution_major_version == "{{ item.distribution_major_version }}"
#  with_items: "{{ repos }}"

#- name: Install monitoring and debuging package
#  yum: name="{{ item }}" update_cache=yes
#  with_items: "{{ packages }}"

- name: Disable selinux
  selinux: state=disabled

- name: Disable firewall
  service: name="firewalld" enabled=no state=stopped

- name: Enable ntpd
  service: name="ntpd" enabled=yes state=restarted

- name: Create admins group
  group:
    name: "{{ sudoers.sudo_group }}"
    state: present

- name: Set cmd alias for /etc/sudoers
  blockinfile:
    dest: /etc/sudoers
    state: present
    block: "{{ sudoers.cmd_alias }}"

- name: Set privileges for admins group
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admins'
    line: '%admins {{ sudoers.cmd }}'

- name: Create administrator accounts
  user:
    name: "{{ item.name }}" 
    password: "{{ item.password }}"
    comment: "{{ item.full_name }}"
    shell: /bin/bash 
    groups: "{{ sudoers.sudo_group }}"
    append: yes 
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  with_items: "{{ accounts }}"

- name: set vm.swappiness in sysctl.conf
  sysctl: name=vm.swappiness value="{{ sysctl.vm.swappiness }}" state=present sysctl_set=yes reload=yes ignoreerrors=yes

- name: Remove temporary gateway
  command: route del default gw "{{ gateway.ip }}"
  ignore_errors: yes
  when: not gateway.keep

- name: Remove persistent gateway
  lineinfile:
    dest: /etc/sysconfig/network
    state: absent
    regexp: '^GATEWAY='
  when: not gateway.keep
