- name: Add epel release
  yum: name="epel-release" state=latest update_cache=true
- name: Add remi release      
  yum: name="{{ remi_url }}" state=present
- name: Clean yum
  command: yum clean all
- name: Install default packages
  yum: name={{ item }} state=latest update_cache=true
  with_items:
  - gcc
  - gcc-c++
  - python-devel
  - openssl-devel
  - zlib-devel
  - atop
  - ioping
  - smartmontools
  - dmidecode
  - sysbench
  - fio
  - lshw
  - iotop
  - iftop
  - nethogs
  - iptraf
  - vim
	- telnet
	- ntp
- name: Autostop iptables and stop iptables
	service: name="iptables" enabled=no state=stopped
- name: Autostart ntpd and start ntpd
	service: name="ntpd" enabled=yes state=restarted
