- name: Change passwd root and enable root login console
  user:
    name: "{{ root_user.name }}"
    password: "{{ root_user.recovery_passwd }}"
    shell: /bin/bash

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    validate: '/usr/sbin/sshd -T -t -f %s'

- name: Restarted sshd
  service: name="sshd" enabled=yes state=restarted
