- include_vars: vault/main.yaml
  tags: include

- name: Remove MariaDB server single
  yum: name="{{ item }}" state=absent
  with_items:
  - MariaDB-server
  - MariaDB-client
  - MariaDB-devel
  when: mariadb_base_version != "10.1"

- name: Install galera
  yum: name="{{ item }}" update_cache=yes
  with_items:
  - galera
  - socat
  - MariaDB-client
  - MariaDB-Galera-server
  - MariaDB-devel
  when: mariadb_base_version != "10.1"

- name: Install galera
  yum: name="{{ item }}" update_cache=yes
  with_items:
  - galera
  - socat
  - MariaDB-client
  - MariaDB-server
  - MariaDB-devel
  when: mariadb_base_version == "10.1"

- name: Create file galera dir
  file: path="{{ mag_galera_dir }}" state=directory owner={{ mariadb_user }} group={{ mariadb_group }}

- name: Enable and start mariadb
  service: name=mysql enabled=yes state=restarted
  tags: restart_mariadb

- name: Create user galera
  mysql_user:
    login_user: "{{ mariadb_root_name }}"
    login_port: "{{ mariadb_port }}"
    login_password: "{{ mariadb_root_passwd }}"
    name: "{{ mag_galera_name }}"
    password: "{{ mag_galera_passwd }}"
    priv: "{{ mag_galera_priv }}"
    state: present
  ignore_errors: yes
  tags: create_galera_user

- name: Config MariaDB Galera Cluster
  template: src=mariadb.conf.j2 dest=/etc/my.cnf.d/server.cnf backup=yes
  tags: reconfig

- name: Check MariaDB status
  command: service mysql status
  tags: check_service

- name: Hello world
  debug: msg="You should start mysql cluster by hand. You could choose the init node"
