nginx_version: nginx-1.11.8
nginx_installation:
  url: "https://nginx.org/download/{{ nginx_version }}.tar.gz"
  group_name: nginx
  user_name: nginx
  full_name: nginx user
  dir: /etc/nginx
  
nginx_compiling_params: "--prefix={{ nginx_installation.dir }} --user={{ nginx_installation.user_name }} --group={{ nginx_installation.group_name }} --without-http_autoindex_module --without-http_ssi_module --without-http_map_module --without-http_uwsgi_module --without-http_scgi_module --without-http_empty_gif_module --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_stub_status_module"

os:
  distribution_centos:
    name: CentOS
    version7: 7
    version6: 6
    version5: 5

nginx_conf:
  pid: /run/nginx.pid
  log_dir: /var/log/nginx
  user: "{{ nginx_installation.user_name }}"
  worker_processes: 1
  worker_connections: 25000
  vhosts_dir: "{{ nginx_installation.dir }}/conf.d"
  upstream: "{{ nginx_installation.dir }}/conf/upstream.conf"
  proxy_cache_path: "{{ nginx_installation.dir }}/conf/proxy_cache_path.conf"
  
nginx_vhosts: "{{ default_nginx_vhosts }}"

frmwrk_php:
  - php
  - php-mysql

processor_php_fpm:
  - php-fpm

php_fpm:
  listen: "{{ default_php_fpm_listen }}"
  listen_owner: nobody
  listen_group: nobody
  listen_mode: 0660
