- include_vars: vault/main.yaml

- name: Copy script install bacula client
  template: src=bacula_client.sh.j2 dest=/tmp/install_bacula_client.sh owner=root group=root mode=0744
  when: is_backup == 1

- name: Run script install bacula client
  shell: /tmp/install_bacula_client.sh
  when: is_backup == 1

- name: Install script
  template:
    src: xtrabackup.sh.j2
    dest: /usr/local/bin/db_backup.sh
    owner: root
    group: root
    mode: 0744
  when: is_backup == 1

- name: Schedule by crontab
  cron:
    name: "Backup db daily"
    minute: 1
    hour: 0
    job: "/usr/local/bin/db_backup.sh"
  when: is_backup == 1
