nginx_version: 1.11.8
nginx_url: "https://nginx.org/download/nginx-{{ nginx_version }}.tar.gz"
nginx_compiling_params: "--prefix={{ nginx_install_dir }} --user={{ nginx_user }} --group={{ nginx_group }} --without-http_autoindex_module --without-http_ssi_module --without-http_map_module --without-http_uwsgi_module --without-http_scgi_module --without-http_empty_gif_module --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_stub_status_module"

nginx_install_dir: /etc/nginx
nginx_vhosts_dir: "{{ nginx_install_dir }}/conf.d"
nginx_log_dir: /var/log/nginx
nginx_cache_dir: /cache/nginx
nginx_conf: "{{ nginx_install_dir }}/conf/nginx.conf"
nginx_proxy_cache_path: "{{ nginx_install_dir }}/conf/proxy_cache_path.conf"
nginx_upstream: "{{ nginx_install_dir }}/conf/upstream.conf"

nginx_pid: /run/nginx.pid
nginx_error_log: "{{ nginx_log_dir }}/error.log"
nginx_access_log: "{{ nginx_log_dir }}/access.log"

nginx_global_params:
  worker_rlimit_nofile: "4096"
  worker_processes: "1"

nginx_events_params:
  worker_connections: "4096"
  use: "epoll"
  multi_accept: "on"

nginx_http_params:
  client_max_body_size: "8M"
  sendfile: "on"
  tcp_nopush: "on"
  tcp_nodelay: "on"
  keepalive_timeout: "65"

nginx_vhosts_name:
  - hotel.example.com

nginx_vhosts:
  - listen: 80
    name: "{{ nginx_vhosts_name.0 }}"
    server_name: "{{ nginx_vhosts_name.0 }} www.{{ nginx_vhosts_name.0 }}"
    index: "index.php index.html"
    log_dir: "{{ nginx_log_dir }}/{{ nginx_vhosts_name.0 }}"
    access_log: "{{ nginx_log_dir }}/{{ nginx_vhosts_name.0 }}/access.log"
    error_log: "{{ nginx_log_dir }}/{{ nginx_vhosts_name.0 }}/error.log"
    client_max_body_size: 20M

    location0: {
        name: /,
        proxy_pass: "http://{{ nginx_vhosts_name.0 }}",
        proxy_set_header: [
          "Host $host",
          "X-Real-IP $remote_addr",
          "X-Forwarded-For $proxy_add_x_forwarded_for",
          "X-Forwarded-Proto $scheme"
        ],
        proxy_cache: "{{ nginx_vhosts_name.0 }}_cache",
        add_header: "X-Proxy-Cache $upstream_cache_status",
        #  If the header includes the "Set-Cookie" field, such a response will not be cached.
        proxy_ignore_headers: "Set-Cookie",
        proxy_cache_use_stale: "error timeout updating http_500 http_502 http_503 http_504",
        proxy_cache_lock: "on",
        proxy_cache_valid: [
          "200 302 10m",
          "301     1h"
        ]
      }

    upstream: {
        name: "{{ nginx_vhosts_name.0 }}",
        server:  ["backend1.localhost:80"]
      }

    cache: {
        cache_dir: "{{ nginx_cache_dir }}/{{ nginx_vhosts_name.0 }}",
        cache_name: "{{ nginx_vhosts_name.0 }}_cache",
        proxy_cache_path: "{{ nginx_cache_dir }}/{{ nginx_vhosts_name.0 }} levels=1:2 keys_zone={{ nginx_vhosts_name.0 }}_cache:10m max_size=1g inactive=60m use_temp_path=off"
    }

### ngx_built: 0|1
ngx_built: 1
### ngx_cache: 0|1
ngx_cache: 1
