version: '2'
services:
  web:
    image: nginx
    hostname: web.simple.flask
    domainname: example.com
    ports:
     - "80:80"
    volumes:
     - ./web/nginx/simple_flask.conf:/etc/nginx/conf.d/simple_flask.conf
    depends_on:
     - app
    networks:
     - my-net
  app:
    build: ./code
    hostname: app.simple.flask
    domainname: example.com
    networks:
    - my-net
networks:
  my-net:
