---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yaml"

- include_vars: vault/main.yaml
  tags: include

- name: Install mysql packages
  include: install_packages.yaml

- name: Config mysql
  include: mysql_config.yaml

- name: Run mysql_secure_installation
  include: mysql_secure.yaml

- name: Run mysql_user_db
  include: mysql_user_db.yaml

- name: Run mysql_replication
  include: mysql_replication.yaml
