version: '2'
services:
  web:
    image: nginx
    container_name: nginx
    ports:
     - "80:80"
    volumes:
     - /app/simple_flask/nginx/simple_flask.conf:/etc/nginx/conf.d/simple_flask.conf
    depends_on:
     - app
    networks:
     - my-net
  app:
    image: xavivn/simple_flask
    container_name: simple_flask
    networks:
    - my-net
networks:
  my-net:
