- name: Setup deployer user
  hosts: all

  tasks:
    - name: Make sure we have deployer group
      group:
        name: "{{ deployer_user.group }}"
        state: present

    - name: Create sudoers for deployer group
      template:
        src: ansible.conf.j2
        dest: "{{ deployer_user.sudo_file }}"
        owner: root
        group: root
        mode: 0440
        validate: 'visudo -cf %s'

    - name: Add deployer user to deployer group
      user:
        name: "{{ deployer_user.name }}"
        password: "{{ deployer_user.passwd }}"
        comment: "{{ deployer_user.full_name }}"
        groups: "{{ deployer_user.group }}"
        append: yes

    - name: Check if filter user in sshd
      command: grep -Fq "AllowUsers" /etc/ssh/sshd_config
      register: check_sshd
      ignore_errors: yes
      changed_when: False
      check_mode: no

    - name: Allow user deployer in sshd
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: 'AllowUsers {{ deployer_user.name }}'
        state: present
        validate: '/usr/sbin/sshd -T -t -f %s'
      when: check_sshd.rc == 0

    - name: Restart sshd
      service: name="sshd" enabled=yes state=restarted
      when: check_sshd.rc == 0

    - name: Copy ssh key to authorized_keys
      authorized_key:
        user: "{{ deployer_user.name }}"
        key: "{{ lookup('file', '/etc/.ssh/ansible_id_rsa.pub') }}"
