cluster_members:
  - 192.168.10.122
  - 192.168.10.123
  - 192.168.10.124

mag_galera_dir: /data/galera
mag_gcache_size: 16M
mag_gcs_recv_q_hard_limit: 16M
mag_gcs_fc_limit: 16
mag_gcs_fc_master_slave: NO
mag_gcs_fc_factor: 0.5
mag_wsrep_cluster_name: ClusterTest
mag_wsrep_slave_threads: 4
mag_wsrep_node_name: NA
mag_wsrep_provider: /usr/lib64/galera/libgalera_smm.so
mag_wsrep_provider_options: "gcache.size={{ mag_gcache_size }};gcache.name = {{ mag_galera_dir }}/galera.cache;gcache.dir={{ mag_galera_dir }};gcs.recv_q_hard_limit={{ mag_gcs_recv_q_hard_limit }};gcs.fc_limit={{ mag_gcs_fc_limit }};gcs.fc_master_slave={{ mag_gcs_fc_master_slave }};gcs.fc_factor={{ mag_gcs_fc_factor }}"
mag_wsrep_log_conflicts: "ON"
mag_wsrep_certify_nonPK: "ON"
mag_wsrep_recover: "OFF"
mag_wsrep_retry_autocommit: 3
mag_wsrep_sst_method: "xtrabackup-v2"

### vault
mag_galera_name: "{{ vault_mag_default_galera_name }}"
mag_galera_passwd: "{{ vault_mag_default_galera_passwd }}"
mag_galera_priv: "{{ vault_mag_default_galera_priv }}"

mariadb_base_version: 10.0
mariadb_version: 10.0.21

mariadb_datadir: /var/lib/mysql
mariadb_datadir_base: /data
mariadb_datadir_origin: "{{ mariadb_datadir_base }}/mysql_datadir"
mariadb_logdir: /var/log/mysqld
mariadb_tmpdir: "{{ mariadb_logdir }}/tmp"
mariadb_log_error: "{{ mariadb_logdir }}/mysql_error.log"
mariadb_slow_query_log_file: "{{ mariadb_logdir }}/mysql_slow.log"
mariadb_general_log_file: "{{ mariadb_logdir }}/mysql_general.log"

mariadb_user: mysql
mariadb_group: mysql
mariadb_port: 3306
mariadb_bind_address: 0.0.0.0
mariadb_socket: "{{ mariadb_datadir }}/mysql.sock"
mariadb_skip_name_resolve: 1

mariadb_default_storage_engine: InnoDB
mariadb_innodb_buffer_pool_size: 2048M
mariadb_innodb_buffer_pool_instances: 1
mariadb_innodb_autoinc_lock_mode: 2
mariadb_innodb_doublewrite: 1
mariadb_innodb_flush_log_at_trx_commit: 1
mariadb_innodb_flush_method: O_DIRECT
mariadb_innodb_log_buffer_size: 16M

mariadb_innodb_file_per_table: 1

mariadb_max_allowed_packet: 32M

mariadb_table_open_cache: 1000


mariadb_query_cache_size: 0
mariadb_query_cache_type: 0

### ma_enable_thread_cache: 0|1
mariadb_thread_cache_size: 4
mariadb_max_connections: 64

mariadb_wait_timeout: 30
mariadb_interactive_timeout: 30
mariadb_connect_timeout: 30

mariadb_tmp_table_size: 64M
mariadb_max_heap_table_size: 64M

mariadb_log_output: FILE
mariadb_log_queries_not_using_indexes: 0
mariadb_log_warnings: 2
mariadb_long_query_time: 2
mariadb_general_log: 0
mariadb_slow_query_log: 1

mariadb_innodb_log_files_in_group: 2
mariadb_innodb_log_file_size: 64M

### ma_enable_thread_pool: 0|1
mariadb_thread_handling: pool-of-threads
mariadb_thread_pool_size: 4
mariadb_extra_port: 6033
mariadb_extra_max_connections: 10

### ma_enable_replication: 0|1
### ma_enable_gtid: 0|1
mariadb_gtid_domain_id: 10
mariadb_report_host: NA
mariadb_report_port: "{{ mariadb_port }}"
mariadb_expire_logs_days: 5
mariadb_server_id: NA
mariadb_max_binlog_size: 200M
mariadb_log_slave_updates: 1
mariadb_binlog_format: ROW

xtrabackup_streamfmt: xbstream

sysctl_vm_swappiness: 10

### vault
mariadb_root_passwd: "{{ vault_mariadb_default_root_passwd }}"
mariadb_root_name: "{{ vault_mariadb_default_root_name }}"
mariadb_root_priv: "{{ vault_mariadb_default_root_priv }}"

### Control param
ma_enable_thread_cache: 1
ma_enable_thread_pool: 0
ma_enable_replication: 1
ma_enable_gtid: 1
