- name: reload nginx
  systemd: name=nginx.service  state=reloaded
  when:
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version7 }}"
