- name: Install php packages
  yum: name="{{ item }}" update_cache=yes enablerepo=remi-{{ php_version }}
  with_items:
    - php
    - php-mysql
    - php-mcrypt
    - php-mbstring
    - php-fpm
    - php-gd
    - php-xml
    - php-pdo
    - php-zip
    - php-bcmath
    - php-memcached
    - php-redis
    - php-soap
    - php-pecl-igbinary
    - php-snmp
    - php-msgpack
    - php-ldap
    - php-process
    - php-json
    - php-mysqlnd
    - php-imap
#    - php-pecl-apcu
    - php-opcache

  when: pfm_enable == 1
  tags: php

- name: Config php-fpm
  template: src=php_fpm.conf.j2 dest=/etc/php-fpm.conf backup=yes
  when: pfm_enable == 1

- name: Config php-fpm.d/www.conf
  template: src=php_fpm.d.www.conf.j2 dest=/etc/php-fpm.d/www.conf backup=yes
  when: pfm_enable == 1

- name: Restart and enable php-fpm
  systemd: name=php-fpm.service enabled=yes daemon_reload=yes state=restarted
  when:
    - pfm_enable == 1
    - ansible_distribution == "{{ distro_centos.name }}"
    - ansible_distribution_major_version == "{{ distro_centos.version7 }}"
