- name: Setup config dir for vhost
  file:
    path: "{{ nginx_conf.vhosts_dir }}"
    owner: nginx
    group: nginx
    mode: 0750
    state: directory

- name: Setup log dir for vhost
  file: 
    path: "{{ item.log_dir }}"
    owner: nginx
    group: nginx
    mode: 0750
    state: directory
  with_items: "{{ nginx_vhosts }}"

- name: Setup root dir for vhost
  file:
    path: "{{ item.root }}"
    owner: nginx
    group: nginx
    mode : 0750
    state: directory
  with_items: "{{ nginx_vhosts }}"
  when: role == "backend"

- name: Setup config for vhost
  template:
    src: nginx.vhosts.conf.j2
    dest: "{{ nginx_conf.vhosts_dir }}/{{ item.name }}.conf"
    owner: nginx
    group: nginx
    mode: 0640
  with_items: "{{ nginx_vhosts }}"
  notify: reload nginx
  tags: vhost_conf

- name: restart and enable nginx
  systemd: name=nginx.service enabled=yes daemon_reload=yes state=restarted
  when:
    - ansible_distribution == "{{ os.distribution_centos.name }}"
    - ansible_distribution_major_version == "{{ os.distribution_centos.version7 }}"
  tags: vhost_conf
