# use docker image - docker in docker
image: docker:latest

before_script:
  - docker info

stages:
  - build
  - test
  - deploy

build:
  script:
    # build
    - docker build -t mattermost_app app/
    - docker build -t mattermost_web web/
    # push image to registry
    - docker tag mattermost_app 103.53.170.69:5000/mattermost_app
    - docker tag mattermost_web 103.53.170.69:5000/mattermost_web
    - docker push 103.53.170.69:5000/mattermost_app
    - docker push 103.53.170.69:5000/mattermost_web
  stage: build
  tags:
    - swat-demo
  only:
    - swat-demo

# deploy to remote server via ssh
deploy:
  before_script:
    - apk update
    - apk add rsync
    - apk add openssh-client
    - chmod +x deploy.sh
  script:
    - ./deploy.sh deployer@103.53.170.70 1102
  after_script:
    - apk del rsync
    - apk del openssh-client
  stage: deploy
  tags:
    - swat-demo
  only:
    - swat-demo
