version: '3'

services:
  db:
    image: mysql
    hostname: mysql.mattermost.swat
    container_name: mysql_mattermost_swat
    volumes:
      - /var/lib/mysql
      - /var/log/mysql
      - ./db/mysql.conf.d:/etc/mysql/mysql.conf.d:ro  ### custom mysql config
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=mmuser_password
      - MYSQL_DATABASE=mattermost

  app:
    image: registry.localhost:5000/mattermost_app
    hostname: app.mattermost.swat
    container_name: app_mattermost_swat
    volumes:
      - ./app/mm-data:/opt/mattermost/data
      - /opt/mattermost/bin
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - MM_SITE_URL=mm.swat.example.com
    depends_on:
      - db

  web:
    image: registry.localhost:5000/mattermost_web
    hostname: nginx.mattermost.swat
    container_name: nginx_mattermost_swat
    ports:
     - "80:80"
     - "443:443"
    environment:
      - SERVER_NAME=mm.swat.example.com
    volumes:
     - /etc/nginx
     - /etc/nginx/conf.d
     ### No need webroot because of proxy role
    depends_on:
     - app
