- name: Build nginx
  include: nginx_build.yaml
  when: ngx_built == 1
  tags: build

- name: Setup nginx global
  include: setup_nginx_global.yaml
  tags: nginx_conf

- name: Install vhosts
  include: vhosts.yaml
  tags: vhost_conf

#- name: Install nginx as proxy
#  include: nginx_proxy.yaml
#  tags: proxy

#- name: Install nginx as cache
#  include: nginx_cache.yaml
#  tags: cache
