- name: Create file upstream.conf
  file:
    path: "{{ nginx_upstream }}"
    mode: 0644
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    state: touch

- name: Config upstream.conf
  template:
    src: nginx_upstream.conf.j2
    dest: "{{ nginx_upstream }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0644
    backup: yes
  with_items: "{{ nginx_vhosts }}"
  notify: restart nginx
