- name: Setup config dir for vhost
  file:
    path: "{{ nginx_vhosts_dir }}"
    owner: nginx
    group: nginx
    mode: 0750
    state: directory

- name: Setup log dir for vhost
  file:
    path: "{{ item.log_dir }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0750
    state: directory
  with_items: "{{ nginx_vhosts }}"

- name: Setup root dir for vhost
  file:
    path: "{{ item.root }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode : 0750
    state: directory
  with_items: "{{ nginx_vhosts }}"
  when: ngx_role == "web"

- name: Setup config for vhost
  template:
    src: nginx.vhosts.conf.j2
    dest: "{{ nginx_vhosts_dir }}/{{ item.name }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0640
  with_items: "{{ nginx_vhosts }}"
  tags: vhost_conf
