mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_pass: "{{ vault_mysql_root_passwd }}"

mysql_db:
  - name: foo
    replicate: yes
  - name: bar
    replicate: no

mysql_users:
  - name: benz
    pass: "{{ vault_mysql_user_passwd }}"
    priv: "*.*:ALL"
    host: "%"

mysql_repl_user:
  - name: repl
    pass: "{{ vault_mysql_repl_passwd }}"
    priv: "*.*:REPLICATION SLAVE"

mysql_repl_role: master
mysql_db_id: 7

mysql_datadir: /var/lib/mysql
mysql_logdir: /var/log/mysqld
mysql_tmpdir: "{{ mysql_logdir }}/tmp"
mysql_log_error: "{{ mysql_logdir }}/mysql_error.log"
mysql_slow_query_log_file: "{{ mysql_logdir }}/mysql_slow.log"
mysql_general_log_file: "{{ mysql_logdir }}/mysql_general.log"
mysql_socket: "{{ mysql_datadir }}/mysql.sock"

mysql_innodb_buffer_pool_size: 2048M
mysql_innodb_buffer_pool_instances: 1
mysql_innodb_log_buffer_size: 16M

mysql_max_allowed_packet: 32M
mysql_table_open_cache: 1000

mysql_thread_cache_size: 4
mysql_max_connections: 64

mysql_tmp_table_size: 64M
mysql_max_heap_table_size: 64M

mysql_log_queries_not_using_indexes: 0
mysql_log_warnings: 2
mysql_long_query_time: 2

mysql_innodb_log_files_in_group: 2
mysql_innodb_log_file_size: 64M

mysql_sql_mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

mysql_report_host: "{{ ansible_host }}"
mysql_report_port: "{{ mysql_port }}"
project_name: mysql-bin
mysql_log_slave_updates: 1
#mysql_binlog_format: ROW or MIXED
mysql_binlog_format: MIXED
mysql_max_binlog_size: 200M
mysql_expire_logs_days: 5
