- name: Copy script setup gitlab runner
  copy: src=setup_gitlab_runner.sh.j2 dest=/tmp/setup_gitlab_runner.sh owner=root group=root mode=0744

- name: Run script setup gitlab runner
  shell: /tmp/setup_gitlab_runner.sh
  args:
    executable: /bin/bash

- include: shared_runner.yaml
  when: runner_type == "shared"
  tags: shared

- include: specific_runner.yaml
  when: runner_type == "specific"
  tags: specific
