- name: Copy script setup gitlab
  copy: src=setup_gitlab.sh.j2 dest=/tmp/setup_gitlab.sh owner=root group=root mode=0744

- name: Run script setup gitlab
  shell: /tmp/setup_gitlab.sh
  args:
    executable: /bin/bash

- name: Has Allow group git in sshd ?
  shell: grep -q AllowGroups "{{ sshd_config }}"
  register: has_allow_groups
  # grep will exit with 1 when no results found.
  # This causes the task not to halt play.
  ignore_errors: true

- name: AllowGroups git in sshd
  lineinfile:
    dest: "{{ sshd_config }}"
    state: present
    line: "AllowGroups {{ git_group }}"
    insertafter: EOF
    validate: "/usr/sbin/sshd -t -f %s"
  when: has_allow_groups|succeeded
  notify: restart sshd

- name: Replace to port 22
  replace:
    dest: "{{ sshd_config }}"
    regexp: 'Port\s+[0-9]+'
    replace: 'Port 22'
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd

- name: Show msg
  debug: msg="Access gitlab via url http://{{ ansible_host }} or http://{{ hostname }}"
