- name: Create proxy cache path
  file:
    name: "{{ item.cache.cache_dir }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0744
    state: directory
  with_items: "{{ nginx_vhosts }}"

- name: Create file proxy_cache_path.conf
  file:
    path: "{{ nginx_proxy_cache_path }}"
    mode: 0644
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    state: touch

- name: Config proxy_cache_path.conf
  template:
    src: nginx_cache.conf.j2
    dest: "{{ nginx_proxy_cache_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0644
    backup: yes
  with_items: "{{ nginx_vhosts }}"
  notify: restart nginx
